SELECT
    EMAIL_ADDRESS AS email,
    WHAT_IS_YOUR_AGE AS age,
    DO_YOU_OWN_A_VR_HEADSET AS vr_headset,
    DO_YOU_PREFER_CATS_OR_DOGS AS cats_or_dogs,
    WHAT_IS_YOUR_CURRENT_STANDING AS standing,
    WHAT_IS_YOUR_FAVORITE_TV_SHOW AS favorite_show,
    "WHEN_DO_YOU_PREFER_TO_TAKE_EXAMS" AS exam_preference,
    "_WHAT_IS_YOUR_PREFERRED_BEVERAGE_" AS preferred_beverage,
    "WHAT_IS_YOUR_FAVORITE_ICE_CREAM_FLAVOR" AS ice_cream_flavor,
    "_WHAT_IS_YOUR_FAVORITE_SEASON_OF_THE_YEAR_" AS favorite_season,
    WHAT_IS_YOUR_FAVORITE_OR_PREFERRED_LLM_TO_USE AS preferred_llm,
    WHAT_FACTOR_INFLUENCES_YOUR_COURSE_SELECTION_THE_MOST AS course_factor,
    WOULD_YOU_DESCRIBE_YOURSELF_AS_AN_EARLY_BIRD_OR_A_NIGHT_OWL AS early_or_night,
    "IF_YOU_HAVE_SECONDARY_MAJORS_PLEASE_LIST_THEM_HERE_SEPARATED_BY_A_COMMA" AS secondary_majors,
    "_WHICH_BEST_DESCRIBES_YOUR_PRIMARY_MAJOR_OR_FIELD_OF_STUDY_IF_YOU_HAVE_MORE_THAN_ONE_MAJOR_PLEASE_SPECIFY_OTHER_MAJORS_AS_PART_OF_THE_NEXT_QUESTION" AS primary_major
FROM {{ source('airbyte_survey_data', 'SURVEY') }}
