SELECT
    TRADE_ID,
    PRICE_BUY * QUANTITY_BUY AS BUY_MONEY,
    PRICE_SELL * QUANTITY_SELL AS SELL_MONEY,
    (PRICE_SELL * QUANTITY_SELL) - (PRICE_BUY * QUANTITY_BUY) AS PROFIT
FROM {{ ref('staging_buy_sell_joint') }}
ORDER BY TRADE_ID
